// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwxtjvdxppsaxarwfsmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3eHRqdmR4cHBzYXhhcndmc21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzMyNjIsImV4cCI6MjA2NDcwOTI2Mn0.FpyyJMNH_FN40ZDdD67f8F3645Gs_ENV49yD898gcKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);